//! Cross-platform data types used by platform traits and implementations.

/// Input device configuration
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct InputDeviceConfig {
    pub capture_keyboard: bool,
    pub capture_mouse: bool,
    pub block_legacy_input: bool,
}

impl Default for InputDeviceConfig {
    fn default() -> Self {
        Self {
            capture_keyboard: true,
            capture_mouse: true,
            block_legacy_input: false,
        }
    }
}

/// Window identifier type
pub type WindowId = usize;

/// Window information
#[derive(Debug, Clone)]
pub struct WindowInfo {
    #[allow(dead_code)]
    pub id: WindowId,
    pub title: String,
    pub process_name: String,
    pub executable_path: Option<String>,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

/// Monitor information
#[derive(Debug, Clone, Copy)]
pub struct MonitorInfo {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

/// Monitor work area (excludes taskbar/Dock). Used on macOS; Windows uses MonitorInfo directly.
#[derive(Debug, Clone, Copy)]
pub struct MonitorWorkArea {
    #[allow(dead_code)]
    pub x: i32,
    #[allow(dead_code)]
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

/// Window frame with position and size
#[derive(Debug, Clone, Copy)]
pub struct WindowFrame {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

impl WindowFrame {
    pub fn new(x: i32, y: i32, width: i32, height: i32) -> Self {
        Self {
            x,
            y,
            width,
            height,
        }
    }

    pub fn center_in(&self, monitor: &MonitorInfo) -> (i32, i32) {
        let x = monitor.x + (monitor.width - self.width) / 2;
        let y = monitor.y + (monitor.height - self.height) / 2;
        (x, y)
    }

    #[allow(dead_code)]
    pub fn aspect_ratio(&self) -> f64 {
        if self.height > 0 {
            self.width as f64 / self.height as f64
        } else {
            0.0
        }
    }

    #[allow(dead_code)]
    pub fn is_valid(&self) -> bool {
        self.width > 0 && self.height > 0
    }
}

/// Trait for window information needed by common operations
pub trait WindowInfoProvider {
    fn x(&self) -> i32;
    fn y(&self) -> i32;
    fn width(&self) -> i32;
    fn height(&self) -> i32;
}

impl WindowInfoProvider for WindowInfo {
    fn x(&self) -> i32 {
        self.x
    }
    fn y(&self) -> i32 {
        self.y
    }
    fn width(&self) -> i32 {
        self.width
    }
    fn height(&self) -> i32 {
        self.height
    }
}

/// Application commands sent from tray menu
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AppCommand {
    ToggleActive,
    ReloadConfig,
    OpenConfigFolder,
    Exit,
}

/// Platform-specific window events generated by the event hook.
#[derive(Debug, Clone)]
pub enum PlatformWindowEvent {
    WindowActivated {
        process_name: String,
        window_title: String,
        window_id: usize,
    },
}

/// Menu action identifiers for tray context menus
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MenuAction {
    None,
    ToggleActive,
    Reload,
    OpenConfig,
    Exit,
}

/// Window context information used for context-aware mappings
#[derive(Debug, Clone, Default)]
pub struct WindowContext {
    pub process_name: String,
    pub window_class: String,
    pub window_title: String,
    pub executable_path: Option<String>,
}

impl WindowContext {
    #[allow(dead_code)]
    pub fn empty() -> Self {
        Self::default()
    }

    #[allow(dead_code)]
    pub fn matches(
        &self,
        process_name: Option<&str>,
        window_class: Option<&str>,
        window_title: Option<&str>,
        executable_path: Option<&str>,
    ) -> bool {
        process_name
            .as_ref()
            .is_none_or(|p| crate::types::wildcard_match(&self.process_name, p))
            && window_class
                .as_ref()
                .is_none_or(|c| crate::types::wildcard_match(&self.window_class, c))
            && window_title
                .as_ref()
                .is_none_or(|t| crate::types::wildcard_match(&self.window_title, t))
            && executable_path.as_ref().is_none_or(|p| {
                crate::types::wildcard_match(
                    self.executable_path.as_deref().unwrap_or(""),
                    p,
                )
            })
    }
}
