//! Cross-platform data types used by platform traits and implementations.

/// Input device configuration
#[derive(Debug, Clone)]
pub struct InputDeviceConfig {
    pub capture_keyboard: bool,
    pub capture_mouse: bool,
    pub block_legacy_input: bool,
}

impl Default for InputDeviceConfig {
    fn default() -> Self {
        Self {
            capture_keyboard: true,
            capture_mouse: true,
            block_legacy_input: false,
        }
    }
}

/// Window identifier type (platform-agnostic)
pub type WindowId = usize;

/// Window information
#[derive(Debug, Clone)]
pub struct WindowInfo {
    pub id: WindowId,
    pub title: String,
    pub process_name: String,
    pub executable_path: Option<String>,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

/// Monitor information
#[derive(Debug, Clone, Copy)]
pub struct MonitorInfo {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

/// Monitor work area excluding taskbar/Dock
///
/// On macOS this excludes the Dock area; on Windows the taskbar
/// is already handled by the OS so this equals [`MonitorInfo`].
#[derive(Debug, Clone, Copy)]
pub struct MonitorWorkArea {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

impl From<MonitorInfo> for MonitorWorkArea {
    fn from(m: MonitorInfo) -> Self {
        Self {
            x: m.x,
            y: m.y,
            width: m.width,
            height: m.height,
        }
    }
}

/// Window frame with position and size
#[derive(Debug, Clone, Copy)]
pub struct WindowFrame {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

impl WindowFrame {
    pub fn new(x: i32, y: i32, width: i32, height: i32) -> Self {
        Self {
            x,
            y,
            width,
            height,
        }
    }

    pub fn center_in(&self, monitor: &MonitorInfo) -> (i32, i32) {
        let x = monitor.x + (monitor.width - self.width) / 2;
        let y = monitor.y + (monitor.height - self.height) / 2;
        (x, y)
    }

    pub fn aspect_ratio(&self) -> f64 {
        if self.height > 0 {
            self.width as f64 / self.height as f64
        } else {
            0.0
        }
    }

    pub fn is_valid(&self) -> bool {
        self.width > 0 && self.height > 0
    }
}

/// Application commands sent from tray menu
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AppCommand {
    ToggleActive,
    ReloadConfig,
    OpenConfigFolder,
    Exit,
}

/// Tray menu actions
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MenuAction {
    None,
    ToggleActive,
    Reload,
    OpenConfig,
    Exit,
}

/// Platform-specific window events generated by the event hook.
#[derive(Debug, Clone)]
pub enum PlatformWindowEvent {
    WindowActivated {
        process_name: String,
        window_title: String,
        window_id: usize,
    },
}

/// Criteria for matching window context
#[derive(Debug, Clone, Default)]
pub struct WindowMatchCriteria {
    pub process_name: Option<String>,
    pub window_class: Option<String>,
    pub window_title: Option<String>,
    pub executable_path: Option<String>,
}

/// Window context information used for context-aware mappings
#[derive(Debug, Clone, Default)]
pub struct WindowContext {
    pub process_name: String,
    pub window_class: String,
    pub window_title: String,
    pub executable_path: Option<String>,
}

impl WindowContext {
    pub fn empty() -> Self {
        Self::default()
    }

    pub fn matches_criteria(&self, criteria: &WindowMatchCriteria) -> bool {
        criteria
            .process_name
            .as_ref()
            .is_none_or(|p| crate::types::wildcard_match(&self.process_name, p))
            && criteria
                .window_class
                .as_ref()
                .is_none_or(|c| crate::types::wildcard_match(&self.window_class, c))
            && criteria
                .window_title
                .as_ref()
                .is_none_or(|t| crate::types::wildcard_match(&self.window_title, t))
            && criteria.executable_path.as_ref().is_none_or(|p| {
                crate::types::wildcard_match(
                    self.executable_path.as_deref().unwrap_or(""),
                    p,
                )
            })
    }

    pub fn matches(
        &self,
        process_name: Option<&str>,
        window_class: Option<&str>,
        window_title: Option<&str>,
        executable_path: Option<&str>,
    ) -> bool {
        let criteria = WindowMatchCriteria {
            process_name: process_name.map(|s| s.to_string()),
            window_class: window_class.map(|s| s.to_string()),
            window_title: window_title.map(|s| s.to_string()),
            executable_path: executable_path.map(|s| s.to_string()),
        };
        self.matches_criteria(&criteria)
    }
}

/// Platform-specific initialization context for notification services
#[derive(Debug, Clone, Default)]
pub struct NotificationInitContext {
    pub native_handle: Option<usize>,
}
